### ISSUE TITLE
Publication Date

### ISSUE THREAD

**Issue by yvesc** [Blog-Core/blog-core#160]
How can I add a publication date field (when the post is published, if published == true) ? (I'm a newbie in Prolog). 
Optional : How can I switch from docstore to , let's say, Mongo ??

**Comment by rla** [comment]
There is date_published field on entry already. It is Unix timestamp of the publication date. It is automatically set when you create a new entry. You can change it afterwards and use arbitrary dates since 1970. The date must be always present.

In the example project it is output using the format_date function:

https://github.com/rla/blog-core-example/blob/fb2f9e6243ec22005557c7cbeadb6bbf64b8d5a8/views/post.html#L14

and here is the function itself

https://github.com/rla/blog-core-example/blob/fb2f9e6243ec22005557c7cbeadb6bbf64b8d5a8/lib/post.pl#L84

Using Mongo is not possible. The docstore api is used directly.
